name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  pypi_release:
    name: Tag release and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - uses: snok/install-poetry@v1.3.2
      - name: Install dependencies
        run: poetry install
      - uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
      - name: Run tests
        run: poetry run pytest -v
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - name: Publish package
        run: poetry publish --build
