name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  pypi_release:
    name: Tag release and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Install the project
        run: uv sync --locked --all-groups --dev

      - uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}

      - name: Run tests
        run: uv run pytest -v

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish --token "${{ secrets.PYPI_API_KEY }}"
