name: Testing

# Run this job on pushes to `main`, and for pull requests. If you don't specify
# `branches: [main], then this actions runs _twice_ on pull requests, which is
# annoying.
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    # Run nightly at 3am Mountain Time (10am UTC)
    - cron: '0 10 * * *'

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-groups --dev

      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      - name: Run tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: uv run pytest -vv --durations=0
